services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    environment:
      - BASE_URL=https://searx.${MY_DOMAIN}
    volumes:
      - ./configs/searxng:/etc/searxng
    labels:
      - "traefik.http.routers.searx.rule=Host(`searx.${MY_DOMAIN}`)" 
    depends_on:
      - traefik
    networks:
      - cloudflare_tunnel

  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_DEFAULTUSER_NAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
    volumes:
      - ./data/gotify:/app/data
    labels:
      - "traefik.http.routers.gotify.rule=Host(`gotify.${MY_DOMAIN}`)" 
    depends_on:
      - traefik
    networks:
      - cloudflare_tunnel
  forgejo:
    image: codeberg.org/forgejo/forgejo:15.0.2
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__ROOT_URL=https://forgejo.${MY_DOMAIN}
    restart: always
    volumes:
      - ./data/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '222:22'
    labels:
      - "traefik.http.routers.forgejo.rule=Host(`forgejo.${MY_DOMAIN}`)" 
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
    depends_on:
      - traefik
    networks:
      - cloudflare_tunnel


  bookstack: 
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack 
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - APP_KEY=${BOOKSTACK_APP_KEY}
      - APP_URL=https://bookstack.${MY_DOMAIN}
      - DB_HOST=bookstack_db
      - DB_PASSWORD=${BOOKSTACK_DB_PASSWORD}
      - DB_USERNAME=${BOOKSTACK_DB_USER}
      - DB_DATABASE=bookstack_db
    volumes: 
        - ./data/bookstack:/config 
    restart: unless-stopped
    labels:
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.${MY_DOMAIN}`)"
    depends_on:
      - bookstack_db
      - traefik
    networks:
      - cloudflare_tunnel

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${MY_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers"
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      SQLITE_DATABASE: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud${MY_DOMAIN}
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: https://nextcloud.${MY_DOMAIN}
      TRUSTED_PROXIES: 172.18.0.0/16
    depends_on:
      - traefik
    networks:
      - cloudflare_tunnel
  mediawiki:
    image: mediawiki:1.46.0 
    container_name: mediawiki
    restart: unless-stopped
    volumes:
      - wiki_images:/var/www/html/images
      - wiki_data:/var/www/data
      - ./data/mediawiki/extensions:/var/www/html/extensions
      - ./configs/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
    labels:
      - "traefik.http.routers.mediawiki.rule=Host(`wiki.${MY_DOMAIN}`)"
    depends_on:
      - traefik
    networks:
      - cloudflare_tunnel


  #openwebui:
    #image: ghcr.io/open-webui/open-webui:main-slim
    #labels:
      #- "traefik.http.routers.openwebui.rule=Host(`openwebui.${MY_DOMAIN}`)"
    #volumes:
      #- ./data/open-webui:/app/backend/data
    #extra_hosts:
      #- "ollama.local:192.168.1.218"
    #depends_on:
      #- traefik
    #networks:
      #- cloudflare_tunnel
